# Ubuntu 22.04 LTS (Jammy)
[image]
base = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"

[resources]
cpus = 6
memory_mb = 6144

[ssh]
user = "rum"

[network]
hostname = "buduntu"

[[ports]]
host = 8080
guest = 8080

[[ports]]
host = 5201
guest = 5201

# [[network.interfaces]]
# network = "netbuntu"
# ip = "192.168.50.10"

# [[mounts]]
# source = "."
# target = "/mnt/project"
# tag = "project"
# inotify = true

[drives.deadpool]
size = "10G"

[drives.pooleo]
size = "10G"

[[fs.zfs]]
drives = ["deadpool", "pooleo"]
target = "/mnt/deadpool"
pool = "deadpool"

[provision.system]
script = "apt-get update && apt-get install -y inotify-tools"

[provision.boot]
script = "echo booted"
